### ISSUE TITLE
1.19.53

### ISSUE THREAD

**Issue by yeetser1155** [gd-codes/mc-pixelart-maker#11]
I want to use this on version 4.3 and for the life of me cant get it to.

**Comment by gd-codes** [comment]
Hi !
The site hosted on github pages always runs only the latest version. You'll need to run that version locally - 

```
git clone https://github.com/gd-codes/mc-pixelart-maker.git && \
cd mc-pixelart-maker && \
git checkout v4.3
```
and then use `python3 -m http.server` or any other way to serve index.html in your browser.
