### ISSUE TITLE
Provide a way to save the image and preferences

### ISSUE THREAD

**Issue by jd-develop** [gd-codes/mc-pixelart-maker#14]
For instance, using cookies, you could store block preferences and the image in case you have to close your browser while you’re doing the map art. It would be very useful.

Don’t hesitate asking me if I’m not precise or you have any questions.

Best regards

**Comment by gd-codes** [comment]
Thanks for your suggestion! I can add a feature where the data is saved to localStorage, in the next update of the web app.

P.S. It may be a short while till I get the free time to make & release the changes. In case anyone would like this urgently, pull requests are welcome :)

**Comment by csemrau** [comment]
I just found your tool and got curious how it works. I already started working on local storage. I can create a PR with my state if you like. It provides manual saving to local storage.

It does not provide a separately saved palette yet, but the palette is saved with the rest of the configuration for an image.
