### ISSUE TITLE
For 3D map with restricted height, the preview does not match the actual map

### ISSUE THREAD

**Issue by csemrau** [gd-codes/mc-pixelart-maker#15]
This is something I noticed when playing around with the options. It does not affect me at the moment, since I'm busy building the flat map I generated.

When the 3D option is enabled with a restricted height limit, like 5, then the preview of the converted image seems to ignore the height restriction. Therefore, it does not match the map that is actually generated. The same applies to the colors shown in the survival guide image.

This is most noticeable when dither is disabled.

Here's an example.

Original image, already resized for a 1x1 map:
<img src="https://github.com/gd-codes/mc-pixelart-maker/assets/6648929/9947fe87-6a62-4172-9f9d-26dc0820bdb2" title="cat resized" width="256" height="256" />

Converting using the full palette, 3D with height limit 5, and no dither.

Preview of converted:
<img src="https://github.com/gd-codes/mc-pixelart-maker/assets/6648929/f78823a1-e5a7-4e6e-b9a1-493621be2361" title="cat preview" width="256" height="256" />

In-game map after running the functions to create the map art:
<img src="https://github.com/gd-codes/mc-pixelart-maker/assets/6648929/7bfa6e4d-8d49-457b-8069-bbc6e025f7de" title="cat map" width="256" height="256" />

I totally understand that, with a restricted height, it is impossible to use all 3 height-dependent shades of a color for every pixel.

A simple improvement would be to consider the truncated heights for the preview and survival guide, which at least provides an accurate preview of what you get.
A better improvement would be to consider the height limit during color conversion, which could lead to better fitting colors.

**Comment by gd-codes** [comment]
Thanks for bringing this up. I was aware that the preview doesn't show the errors due to height restriction, and can add your suggested improvements in the next update of the web app.

P.S. It may be a short while till I get the free time to make & release the changes. In case anyone would like this urgently, pull requests are welcome :)
