### ISSUE TITLE
Tooltip in survival guide covers block above

### ISSUE THREAD

**Issue by csemrau** [gd-codes/mc-pixelart-maker#18]
I am building my flat map top to bottom, and the tooltip showing the next block to place covers the block directly above. If the block above was clearly visible, I could more easily confirm that I'm still on track and did not miscount.
Putting the tooltip below would work for me, but could likewise annoy when a map is built bottom to top.
Maybe the tooltip can have an extended arrow so it sits one row higher above the block. 🤔 

![image](https://github.com/gd-codes/mc-pixelart-maker/assets/6648929/c617d3d7-df9b-4ecd-b8ce-22d0f34e2a11)

**Comment by gd-codes** [comment]
I have a fix for this, will push it soon!
