### ISSUE TITLE
Native tooltip vanishes after using the fancy tooltip

### ISSUE THREAD

**Issue by csemrau** [gd-codes/mc-pixelart-maker#26]
Noticed this, but it does not disturb me ATM.

In the survival guide, each cell has its native tooltip via its `title` attribute, which allows for a quick check of a color without losing the focused cell. When the fancy tooltip is opened for a cell, the `title` attribute is empty and the former title can only be found in `data-original-title`. When the fancy tooltip is closed, the `title` attribute is not restored.

In this image, the first row had its fancy tooltip opened and lost the native tooltip shown here for a cell in the second row.
![image](https://github.com/gd-codes/mc-pixelart-maker/assets/6648929/1acd9968-5057-488a-bbce-49d258aabfa7)

**Comment by gd-codes** [comment]
This seems to be a [bug in Bootstrap](https://github.com/twbs/bootstrap/issues/15359) itself. I can probably add a fix [like this](https://stackoverflow.com/questions/42759934/bootstrap-popover-with-html-title-tooltip) to explicitly restore the title on focusout, when the fancy popover is closed.
