### ISSUE TITLE
Allow customization of block per color

### ISSUE THREAD

**Issue by csemrau** [gd-codes/mc-pixelart-maker#32]
For each color, there are often several blocks one can choose. The survival guide uses one fixed label in the summary and tool tips.

Since I use a different block for several of these colors, I have to translate the guide color in my head to my choice of block. Translating "Yellow Dye" to "Yellow Wool" is easy enough. Translating "Orange Dye" to "Undyed Terracotta" is harder. 😄 

I wonder if it is feasible to allow customizing the choice of block, and of course to also save that choice in local storage with the rest of the configuration.

A dirty hack that I just implemented is good enough for my needs at the moment (basically, a hard-coded name override), so this feature request is "nice to have" from my POV.

**Comment by gd-codes** [comment]
You can now edit the names in the colour selection modal before processing the image, and it will be reflected in the UI subsequently.
