### ISSUE TITLE
Add a way to don't see an specific block or only see one block.

### ISSUE THREAD

**Issue by CryView** [gd-codes/mc-pixelart-maker#35]
I'm doing a mapart right now and the biggest problem I'm having it's difference between the blocks with very similars blocks. So that makes me see what is each individual block, doing the proccess very slow

**Comment by gd-codes** [comment]
If i've understood correctly, do you mean that you would like an option to hide/show blocks in the survival guide panel?
This feature is possible to add 👍

**Comment by CryView** [comment]
Yes, that's what I want
