### ISSUE TITLE
Minecraft PE Android

### ISSUE THREAD

**Issue by Bluefox1995** [gd-codes/mc-pixelart-maker#4]
How do you use these on Mcpe android? I don't seem to find a way to use it. Your website definitely say android too.Please guide me.

**Comment by gd-codes** [comment]
Once you download the `.mcpack` file from the site, the procedure is the same as it is to apply any behaviour pack to Minecraft on Android -

- Find the file in the settings / file explorer or some other android file browser app that you may be using.
- The Minecraft app must be already installed, clicking the downloaded pack should open it directly with the game and import it.
- Then you have to apply the pack to your world from that world's settings > Behaviour packs.

This is according to the [official instructions provided by Microsoft/Mojang here](https://docs.microsoft.com/en-us/minecraft/creator/documents/addonpackinstallation?tabs=android).

**Comment by Bluefox1995** [comment]
im still not clear. i downloaded the .mcpack.zip file and then unzipped it. the files are .json and .mcstructure . Minecarft is installed in my device , clicking which specific file directly imports the file into the game? None. How do you apply the pack to behaviour packs? There are 2 behaviour pack folders. one for the minecraft as whole and another for the specific world. i copy pasted the .mcpack file on both behaviour packs folder but still does not seem to work. Am i doing something wrong?

**Comment by Bluefox1995** [comment]
ignore all my above 2nd questions because i figured it out. when i download the file it comes as .mcpack.zip and all i had to do was rename and remove .zip. After this .mcpack will open in minecraft and now the 3rd problem has arised. 
Pack fails to load everytime. 
pack id: xxxxxxx
pack version:1.0.0
file location:xxxxx
error: unable to find manifest in pack
do you have any idea where i went wrong?

**Comment by Bluefox1995** [comment]
Again ignore my 3rd questions above. I just had wrong version for importing the file. I upgraded to latest version and .mcpack has succesfully loaded but i was again confused for a while because a world didnt appeared with that file. so i created the new creative flat world with the behaviour pack which is .mcpack file enabled and still there was nothing. then i used the command /function file name/1 and it finally appeared.

**Comment by gd-codes** [comment]
Yes, after applying the add-on, the procedure for running the commands is the same on any device/OS. That's [described on the site](https://gd-codes.github.io/mc-pixelart-maker/manual.html#in-mc) itself.

Glad to hear that it finally worked!
