### ISSUE TITLE
Map incomplete

### ISSUE THREAD

**Issue by TheNoobTrollTheMeme** [gd-codes/mc-pixelart-maker#5]
@
![Screenshot_2022-07-13-07-57-59-741_com mojang minecraftpe](https://user-images.githubusercontent.com/109186632/178618089-b0b37124-1074-4f49-9ce0-bed2730de7e6.jpg)
I already made the simulation distance to 8. Pls fix. Thx

**Comment by gd-codes** [comment]
You can try this new setting while generating the behaviour pack -
<img width="724" alt="image" src="https://user-images.githubusercontent.com/45459312/185778218-312a8546-4126-42f8-bb76-61e714edfa33.png">

Minecraft continues to load structures placed outside simulated chunks when you go near enough, instead of leaving the area empty, so this is a solution to the problem.

**Comment by linh772006** [comment]
Hey How can i fixx this i change render distance to 9-12 but can fix it
![image](https://user-images.githubusercontent.com/114301655/192106180-37570ecf-c45e-422b-ace8-f7e3233bc38d.png)![image](https://user-images.githubusercontent.com/114301655/192106187-1dfc0ef1-2682-4665-8d93-4bded74439b7.png)

**Comment by gd-codes** [comment]
Hi !
You mentioned that you had changed the "render distance". There are actually 2 different settings within minecraft - Simulation distance and Render distance, and they're not the same thing. 

For this to work **Simulation** distance is the one that needs to be large enough (_greater than_ 8). You can find it in the world settings (not video settings) - near the World Seed etc.

P.S. :  Are you playing on a local world, or a server/realm ? I believe it may not always be possible to change the sim distance on servers/realms. For local worlds that you created on your device, just exit the world and open the settings page.

Also, the [fix](https://github.com/gd-codes/mc-pixelart-maker/issues/5#issuecomment-1221476955) that I last posted, the checkbox on the website that says "_Use only structures..._", should fix this irrespective of what the simulation distance is, based on my testing. Did you enable that option too while generating the pack ?

**Comment by dengkuhahaha-cmd** [comment]
<img width="1612" height="720" alt="Image" src="https://github.com/user-attachments/assets/b57e80ac-83cd-401c-ad3d-da4f649299e5" /> So I did the simulation of my world to the max (which is 8) and I set my render distance to 10. And finally it loaded the image but there's something that bothers me and that's the green line on the map, that green line is a space that it didn't cover up by blocks. Tho it made the map it is still not full as you can see on the screenshot there's still missing blocks ( in one straight line above every map ). Please notice this.

**Comment by dengkuhahaha-cmd** [comment]
> <img alt="Image" width="1612" height="720" src="https://private-user-images.githubusercontent.com/234595122/494373763-b57e80ac-83cd-401c-ad3d-da4f649299e5.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg4ODQwNjYsIm5iZiI6MTc1ODg4Mzc2NiwicGF0aCI6Ii8yMzQ1OTUxMjIvNDk0MzczNzYzLWI1N2U4MGFjLTgzY2QtNDAxYy1hZDNkLWRhNGY2NDkyOTllNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkyNlQxMDQ5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTc2MWVjMGNlNWFkNzVkYTU2NzZjY2RiZWM2NjVmZjBlZWM4YjIzZDE5YTk3OTAwNzBlYzFmZjQ5NDA2NzA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jyjF74gGBXOIXiYQnpQiYzDH4LeMGglUL12DKhDK36w"> So I did the simulation of my world to the max (which is 8) and I set my render distance to 10. And finally it loaded the image but there's something that bothers me and that's the green line on the map, that green line is a space that it didn't cover up by blocks. Tho it made the map it is still not full as you can see on the screenshot there's still missing blocks ( in one straight line above every map ). Please notice this.

Also I notice why the old version of this website works properly and I got really no problem when Iam using this? I don't increase my simulation and render distance I just set up the pack and downloaded it then import it to Minecraft then simple /function command and it just work perfectly. Is there any way I can use the old version of this?
